CREATE FUNCTION [tools].[fu_DateInt] (@date DATE)
--DROP FUNCTION [tools].[fu_DateInt]

RETURNS INT

AS

BEGIN

DECLARE @return INT

SET @return = ISNULL(
RIGHT(LTRIM(RTRIM('0000'+CAST(DATEPART(YEAR,@date)  AS CHAR))),4)+
RIGHT(RTRIM(LTRIM('00'+CAST(DATEPART(MONTH,@date) AS CHAR))),2)+
RIGHT(RTRIM(LTRIM('00'+CAST(DATEPART(DAY,@date) AS CHAR))),2),0)

RETURN @return

END